// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "58839f29-3545-4f5e-aba7-0bbb547396c2");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1632245059);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1632245042);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1632245040);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1632245089);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 798720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1632245029);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ae6f9288-db7a-40a2-9aa6-d668a8f8a23f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1632245063169");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1632246869169");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1632245044252");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1632266644252");
user_pref("browser.slowStartup.averageTime", 12965);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210804193512");
user_pref("browser.startup.homepage_override.mstone", "78.13.0");
user_pref("browser.startup.lastColdStartupCheck", 1632245034);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.13.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "15dafa697c35474fa07db250d1765b3e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.13.0");
user_pref("extensions.lastPlatformVersion", "78.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"bf57e3f2-b3c4-4d8b-aea0-64e58f4bef62\",\"formautofill@mozilla.org\":\"7d5d38ab-0070-4bea-ba27-b003efe0af50\",\"screenshots@mozilla.org\":\"e4a1b30e-d224-4cf3-a062-1883cdd973ec\",\"webcompat-reporter@mozilla.org\":\"4b98e324-e108-49e0-b57d-dde61c86dbe5\",\"webcompat@mozilla.org\":\"7e006f26-7515-45b0-82b1-1c6f1e7a5a40\",\"default-theme@mozilla.org\":\"ce30265a-12f7-4bb6-8737-ceea28a3bcc9\",\"google@search.mozilla.org\":\"df0b2f72-9011-425a-b20d-1dd0b48db2b1\",\"amazondotcom@search.mozilla.org\":\"e3613bff-e71b-4a2d-838d-9f34a72eda36\",\"wikipedia@search.mozilla.org\":\"ddb03f37-dac9-4ddd-9692-c1e2eae6aa91\",\"bing@search.mozilla.org\":\"631c42f8-9c21-4dfa-b92a-e70b694980bc\",\"ddg@search.mozilla.org\":\"0f071d35-ab55-4c7d-b7fc-2d6163907ce8\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "8575921f-5af0-4d32-b0c9-cb7e938c3f34");
user_pref("security.sandbox.plugin.tempDirSuffix", "42b61df2-44af-4b60-a568-15e3c8529714");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1632245021);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210804193512");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
